AllCops:
  TargetRubyVersion: 2.3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - lib/capistrano/tasks/deploy.rb
